---
title: "COVID 19 Statistics"
author: "Donald Jackson"
date: '`r Sys.Date()`'
output: 
  html_document:
    code_folding: hide
params:
  flagIso3c:
    input: text
    label: Country to highlight
    value: USA
---

# Objective

Use Johns Hopkins COVID data to plot cases and deaths worldwide and in selected country.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# get country from input
flagIso3c <- params$flagIso3c

```

```{r packages}
suppressPackageStartupMessages({
  library(tidyverse)
  library(lubridate)
  library(viridis)
  library(plotly)
})
```

```{r datasets}
cases <- read_csv(
  "https://joachim-gassen.github.io/data/jh_covid19_data_2020-03-24.csv",
  col_types = cols()
) %>%
  mutate(date = ymd(date))

demog <- read_csv(
  "https://joachim-gassen.github.io/data/jh_add_wbank_data.csv", 
  col_types = cols()
)

data <- left_join(cases, demog, by = "iso3c")

data <- mutate(data, cases_percapita = (confirmed / population),
               deaths_percpita = (deaths / population),
               death_rate = (deaths/confirmed))

# check that flagIso3c is in dataset
if( !(flagIso3c %in% data$iso3c)) {
  stop("Highlight country ", flagIso3c, " not found in dataset")
}

# get country code
flagCountry <- filter(cases, iso3c == flagIso3c) %>% 
  slice(1) %>% 
  pull(country)

# define manual color scale
flagColors <- c("red", "grey50")
names(flagColors) <- c(flagIso3c, "Others")

```

## Worldwide cases


```{r last_cases}
# last reported casenumber and deaths

last <- data %>%
  group_by(country) %>%
  arrange(desc(date)) %>%
  slice(1) %>%
  ungroup() 

# plot cases, remove uncoded countries
plot_bycountry <- filter(last, !is.na(iso3c)) %>%
  ggplot(aes(x = fct_reorder(country, confirmed, .desc = T),
             y = confirmed, 
             color = ifelse(iso3c == flagIso3c, flagIso3c, "Others"))) +
  labs(x = "Country", y = "Confirmed Cases",
       color = "Country",
       title = "Confirmed Cases by Country") +
  scale_color_manual(values = flagColors) +
  stat_identity() +
  scale_y_log10() +
  theme_minimal() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

plot_bycountry

# make interactive
ggplotly(plot_bycountry, tooltip = c("x", "y"))

```

```{r cases vs population}
# plot confirmed cases vs population

plot_caseVpop <- filter(last, !is.na(iso3c) & !is.na(population)) %>%
  ggplot(aes(x = population, y = confirmed, fill = iso3c,
             color = ifelse(iso3c == flagIso3c, flagIso3c, "Others"))) +
  stat_smooth(method = "lm", formula = y~ x,
              aes(color = NA, fill = NA),
              color = "black", linetype = "dotted") +
  geom_point() +
  labs(color = "Country",
       title = "Cases vs. Population") +
  scale_color_manual(values = flagColors) +
  scale_x_log10() +
  scale_y_log10() +
  theme_minimal() +
  guides(fill = FALSE)

# print static
plot_caseVpop

# make interactive
ggplotly(plot_caseVpop, 
         tooltip = c("confirmed", "population", "iso3c"))

```

```{r deaths vs cases}

last %>% 
  filter(confirmed > 1 & deaths > 1) %>% 
  ggplot(aes(x = confirmed, y = deaths)) +
  stat_smooth(method = "lm", formula = y ~ x) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "Cases", y = "Deaths", title = "Deaths vs Cases") +
  theme_minimal()

```


# Cases in `r flagCountry`

```{r flag_cases}
flagCases <- filter(data, iso3c == flagIso3c)

# plot cases per time
f_caseVday <- flagCases %>%
  ggplot(aes(x = date, y = confirmed)) +
  scale_y_log10() +
  stat_smooth(method = "lm", formula = y ~ x) +
  geom_point() +
  labs(title = paste(flagCountry, "Cases by Date")) +
  theme_minimal()

ggplotly(f_caseVday)

# plot deaths
f_deathsVday <- flagCases %>%
  filter(deaths > 0) %>%
  ggplot(aes(x = date, y = deaths)) +
  scale_y_log10() +
  stat_smooth(method = "lm", formula = y ~x) +
  geom_point() +
  labs(title = "US Deaths by Date",
       x = "Deaths", y = "Date") +
  theme_minimal()

ggplotly(f_deathsVday)

# plot death rate over time
f_deathRateVday <- flagCases %>%
  filter(death_rate > 0) %>%
  ggplot(aes(x = date, y = death_rate)) +
  geom_point(aes(color = log10(confirmed))) +
  scale_color_viridis() +
  labs(title = paste(flagCountry, "Death Rate by Date"),
       x = "Date", y = "Deaths/Cases", color = "log10(Cases)") +
  theme_minimal()

ggplotly(f_deathRateVday)

```