---
title: "US Covid Rates"
author: "Donald Jackson"
date: '`r Sys.Date()`'
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 3
params:
  highlightState:
    input: text
    label: State to highlight
    value: Massachusetts
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

# get state to highlight
highlightState <-  params$highlightState
```

# Objective

Generate exploratory visualizations for US COVID-19 infection and death rates using data from the New York Times.

```{r packages}

suppressPackageStartupMessages({
  library(tidyverse)
  library(lubridate)
  library(viridis)
  library(plotly)
  library(envDocument)
  library(knitr)
	library(git2r)
	library(here)
	library(ggToys)
	library(rjson)
})

```

```{r set_defaults}
# set default ggplot theme
ggplot2::theme_set(theme_dj())

```

## Data

Data is compiled by the New York Times and posted to Github at https://github.com/nytimes/covid-19-data.  Data is updated daily.

```{r check_data_status}
dataDir <- paste(here::here(), "data", "nyt_us", sep = "/")

# refresh data if older than 'staleness' hours
staleness <- 24 

# need to add code to check if data is current.
# right now I'm pulling it in as a submodule.
lastDataCommit <- git2r::last_commit(dataDir)

commitTime <- as.POSIXct(lastDataCommit$author$when)

age <- as.numeric((Sys.time() - commitTime), units = "hours")

# if data is old, update data and time
if(age >= staleness) {
	git2r::pull(dataDir)
	
	lastDataCommit <- git2r::last_commit(dataDir)

	commitTime <- as.POSIXct(lastDataCommit$author$when)

}

```

Using data from
`r format.Date(commitTime, format = "%B %d %Y %T", tz = "", usetz = T)`

```{r load_state_data}
# load state-level data
stateFile <- paste(dataDir, "us-states.csv", sep  =  "/")

stateData <- read.csv(stateFile, header = T, stringsAsFactors = F)

# convert date
stateData$date <- as.Date(stateData$date, format = "%Y-%m-%d")

# get most recent data
lastStateData <- stateData %>%
	group_by(state) %>%
	arrange(desc(date), .by_group = T) %>%
	slice(1) %>%
	ungroup()

# Values for cases and deaths are cumulative, need to get new
stateData <- stateData %>%
	group_by(state) %>%
	arrange(date, .by_group = T) %>%
	mutate(new_cases = cases - lag(cases, default = first(cases)),
				 new_deaths = deaths - lag(deaths, default = first(deaths))) %>%
	ungroup()


```

```{r load_county_data}
# load cases by county
countyDataFile <- paste(dataDir, "us-counties.csv", sep = "/")

countyData <- read.csv(countyDataFile, header = T, stringsAsFactors = F,
											 colClasses = c("fips"="character"))

countyData$date <- as.Date(countyData$date, format = "%Y-%m-%d")

lastCountyData <- countyData %>% 
	group_by(fips) %>%
	arrange(desc(date)) %>%
	slice(1) %>%
	ungroup()
```

```{r load_maps}
# load county map
countyMapUrl = 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'

countyMapData<- rjson::fromJSON(file=countyMapUrl)


```


# Results

## State-Level

### Cases
```{r cases_byStateDate}
# plot cumulative cases by state
casesByState <- lastStateData %>%
	mutate(state = fct_reorder(state, cases, .desc = F),
				 cases = ifelse(cases < 1, (cases + 0.1), cases) )%>%
	highlight_key(~state, group = "byState") %>%
	ggplot(aes(x= state, y = cases)) +
	geom_point() +
	scale_y_log10() +
	scale_x_discrete(expand = expansion(add = 1)) +
	labs(title = "Total Cases By State",
			 y = "Cases", x = "State") +
	theme(axis.text.x = element_blank(),
				axis.ticks.x = element_blank(),
				panel.grid.minor.x = element_blank(),
				panel.grid.major.x = element_blank())


p_casesByState <- ggplotly(casesByState, tooltip = c("state", "cases")) %>%
	hide_guides() #%>%
# 		highlight(dynamic = T, selectize = T, persistent = F,
# 						on = "plotly_click",
#   					defaultValues = highlightState)

# p_casesByState

# plot growth in cases by state
caseGrowthByState <- stateData %>%
	mutate(cases = ifelse(cases <1, (cases + 0.1), cases)) %>%
	highlight_key(~state, group = "byState") %>%
	ggplot(aes(x = date, y = cases)) +
	geom_line(aes(group = state)) +
	labs(title = "Case Growth By State", 
			 x = "Date", y = "Cases") +
	scale_y_log10()

p_caseGrowthByState <- ggplotly(caseGrowthByState) %>%
	hide_guides() #%>%
# 	highlight(dynamic = T, selectize = T, persistent = F,
# 						on = "plotly_click",
#   					defaultValues = highlightState)

# p_caseGrowthByState

subplot(p_casesByState, p_caseGrowthByState,
				widths = c(0.25, 0.75),
				shareX = F, shareY = T,
				which_layout = 1) %>%
			highlight(dynamic = T, selectize = T, persistent = F,
						on = "plotly_click",
  					defaultValues = highlightState)

```

```{r new_cases_by_state}
# plot 3 day rolling average
newCasesState <- stateData %>%
	group_by(state) %>%
	arrange(date, .by_group = T) %>%
	mutate(prev_cases = lag(new_cases, 1), 
				 prev_by2_cases = lag(new_cases, 2)) %>%
	ungroup() %>%
	mutate(rmean_new_cases = 0.1 + select(., new_cases, prev_cases, prev_by2_cases) %>%
				 	rowMeans(., na.rm = T)) %>%
	highlight_key(~state, group = "byState") %>%
	ggplot(aes(x = date, y = rmean_new_cases)) +
	geom_line(aes(group = state)) +
	labs(y = "New Cases (3 day average)", x = "Date",
			 title = "New Cases By State") +
	scale_y_log10()

# newCasesState

p_newCasesState <- ggplotly(newCasesState) %>%
	hide_guides() %>%
	highlight(dynamic = T, selectize = T, persistent = F,
						on = "plotly_click",
						defaultValues = highlightState)

p_newCasesState

```

### Deaths 
```{r deaths_byState}
# plot cumulative cases by state
deathsByState <- lastStateData %>%
	mutate(state = fct_reorder(state, deaths, .desc = T),
				 deaths = ifelse(deaths < 1, (deaths + 0.1), deaths))%>%
	highlight_key(~state, group = "byState") %>%
	ggplot(aes(x = state, 
						 y = deaths)) +
	geom_point() +
	scale_y_log10() +
	scale_x_discrete(expand = expansion(add = 1)) +
	labs(title = "Total Deaths By State",
			 y = "Deaths", x = "State") +
	theme(axis.text.x = element_blank(),
				axis.ticks.x = element_blank(),
				panel.grid.minor.x = element_blank(),
				panel.grid.major.x = element_blank())


p_deathsByState <- ggplotly(deathsByState, tooltip = c("state", "deaths")) %>%
	hide_guides() #%>%
	# highlight(dynamic = T, selectize = T, persistent = F,
						# on = "plotly_click",
  					# defaultValues = highlightState)

deathsGrowthByState <- stateData %>%
	mutate(deaths = ifelse(deaths <1, (deaths + 0.1), deaths)) %>%
	highlight_key(~state, group = "byState") %>%
	ggplot(aes(x = date, y = deaths)) +
	geom_line(aes(group = state)) +
	labs(title = "Death Growth By State", 
			 x = "Date", y = "Deaths") +
	scale_y_log10()

p_deathsGrowthByState <- ggplotly(deathsGrowthByState) %>%
	hide_guides()

subplot(p_deathsByState, p_deathsGrowthByState,
				widths = c(0.25, 0.75),
				shareX = F, shareY = T,
				which_layout = 1) %>%
			highlight(dynamic = T, selectize = T, persistent = F,
						on = "plotly_click",
  					defaultValues = highlightState)

```

### Fatality Rate By State
```{r state_deathsPerCase}
p_cfrByState <- lastStateData %>%
	filter(deaths > 0) %>%
	highlight_key(~state, group = "byState") %>%
	ggplot(aes(x = cases, y = deaths)) +
	stat_smooth(method = "lm", formula = y ~ x) +
	geom_point() +
	labs(title = "Cumulative Deaths vs. Cases",
			 x = "Cases", y = "Deaths") +
	scale_x_log10() +
	scale_y_log10()

ggplotly(p_cfrByState, tooltip = c("all")) %>%
	hide_guides() %>%
	highlight(dynamic = T, selectize = T, persistent = F,
						on = "plotly_click",
  					defaultValues = highlightState)
```

```{r state_cfrByDate}
p_cfrByStateDate <- stateData %>%
	filter(deaths > 0) %>%
	highlight_key(~state, group = "byState") %>%
	ggplot(aes(x = date, y = (deaths/cases), 
						 group = state)) +
	labs(title = "State Death Rates By Date", x = "Date",
			 y = "Death Rate", color = "log10 Cases") +
	geom_line()

ggplotly(p_cfrByStateDate, tooltip = c("all")) %>%
	hide_guides() %>%
	highlight(dynamic = T, selectize = T, persistent = F,
						on = "plotly_click",
  					defaultValues = highlightState)
```

### Map Plot

```{r caseMap, eval = T}

p_caseMap <- plot_ly() 

p_caseMap <- p_caseMap %>% add_trace(
    type= "choroplethmapbox",
    geojson = countyMapData,
    locations = lastCountyData$fips,
    z = log10(lastCountyData$cases + 1),
    colorscale = "Viridis",
    zmin = 0,
    zmax = 5,
    marker = list(line = list(
      width = 0),
      opacity = 0.5
    )
  )

p_caseMap <- p_caseMap %>% layout(
    mapbox = list(
      style = "carto-positron",
      zoom  = 2,
      center = list(lon =  -95.71, lat = 37.09))
)

p_caseMap
```
